### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by pvulakh** [JeffChoJC/openRes#2]
Great work on this! A few things to change:
### `users` table:
- [x] Replace the `username` column with `fname` and `lname`

### `reservations` table:
- [x] Remove the `unique` part of your indices on `date` and `time` (so multiple users can reserve a restaurant on 05/23/2019, for example)
- [x] If you'd like an index to prevent a specific user from having multiple reservations at the same date and time, you can add a composite index on [:user_id, :date, :time]

### `reviews` table
 - [x] Remove the `unique` part of the index on `:user_id` - if you leave this on, it means a user can only ever write one review!

Again, really good job here :) let me know if you have any questions!

**Comment by JeffChoJC** [comment]
If I don't require unique for either `date` or `time`, how can I ensure there aren't overlapping reservations?

**Comment by JeffChoJC** [comment]
Would I implement the composite index like so: 

add_index(:user, [:user_id, :date, :time])

Also, how is this different from indexing each of these columns separately?
